//! Integration tests using real CyberArk SAML assertion and IDP certificate.
//! These test files are in sample_files/ at the project root.

use std::path::PathBuf;

fn sample_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("sample_files")
}

fn assertion_xml() -> String {
    std::fs::read_to_string(sample_dir().join("assertion_response.xml")).unwrap()
}

fn idp_cert_path() -> PathBuf {
    sample_dir().join("hyperdrive-2fa-np_bswhealth_org_cert.cer")
}

#[test]
fn test_real_assertion_structure() {
    let xml = assertion_xml();

    // Should parse assertion details (note: parser may pick up whitespace
    // from indented XML — that's a known limitation with the sample file)
    let details = seahorse::saml::parser::extract_assertion_details(&xml).unwrap();
    assert!(details.has_signature);
    println!("Assertion ID: {}", details.assertion_id);
    println!("Issuer: '{}'", details.issuer);
    println!("Subject: '{}'", details.subject);
}

#[test]
fn test_real_assertion_validation_without_idp_cert() {
    let xml = assertion_xml();
    let report = seahorse::saml::validator::validate_assertion(&xml, None);

    println!("\n=== Validation Report (no IDP cert) ===");
    println!("Summary: {:?}", report.summary);
    for check in &report.checks {
        let icon = if check.passed { "PASS" } else { "FAIL" };
        println!("  [{}] {}: {}", icon, check.name, check.detail);
        if let Some(ref diag) = check.diagnostic {
            println!("        Diagnostic: {}", diag);
        }
    }
    println!("Algorithm: {}", report.algorithm);
    println!("Cert Subject: {}", report.cert_subject);

    // Structure should always pass
    assert!(
        report.checks.iter().any(|c| c.name == "Structure" && c.passed),
        "Structure check should pass"
    );
}

#[test]
fn test_real_assertion_validation_with_idp_cert() {
    let xml = assertion_xml();
    let trust_store =
        seahorse::saml::trust::load_idp_certificates(&idp_cert_path()).unwrap();

    println!("IDP leaf cert CN: {}", seahorse::saml::trust::cert_cn(&trust_store.leaf_cert));
    println!("Chain certs: {}", trust_store.chain_certs.len());

    let report = seahorse::saml::validator::validate_assertion(&xml, Some(&trust_store));

    println!("\n=== Validation Report (with IDP cert) ===");
    println!("Summary: {:?}", report.summary);
    for check in &report.checks {
        let icon = if check.passed { "PASS" } else { "FAIL" };
        println!("  [{}] {}: {}", icon, check.name, check.detail);
        if let Some(ref diag) = check.diagnostic {
            println!("        Diagnostic: {}", diag);
        }
    }
}

#[test]
fn test_real_assertion_digest_debug() {
    let xml = assertion_xml();

    // Step 1: Remove signature
    let body = seahorse::saml::c14n::remove_signature_element(&xml).unwrap();
    println!("\n=== After removing Signature ===");
    println!("Body length: {} bytes", body.len());
    println!("First 200 chars:\n{}", &body[..body.len().min(200)]);

    // Step 2: Canonicalize
    let canon = seahorse::saml::c14n::canonicalize_exclusive(&body, &[]).unwrap();
    let canon_str = String::from_utf8_lossy(&canon);
    println!("\n=== Canonicalized body ===");
    println!("Length: {} bytes", canon.len());
    println!("Content:\n{}", canon_str);

    // Step 3: Compute digest
    let digest = openssl::hash::hash(openssl::hash::MessageDigest::sha256(), &canon).unwrap();
    let digest_b64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &digest);
    println!("\n=== Digest ===");
    println!("Computed: {}", digest_b64);
    println!("Expected: nbJYMYhftw5CDO+9NBOC5clLg0Vtve3Io6mg2fnfN6E=");
    println!("Match: {}", digest_b64 == "nbJYMYhftw5CDO+9NBOC5clLg0Vtve3Io6mg2fnfN6E=");
}

#[test]
#[ignore] // Requires running the Python lxml reference script first
fn test_c14n_matches_lxml_reference() {
    // Compare our c14n output against lxml's on the clean compact form.
    // The lxml reference was generated by:
    //   parser = etree.XMLParser(remove_blank_text=True)
    //   doc = etree.fromstring(xml, parser); strip_text_ws(doc)
    //   sig.getparent().remove(sig)
    //   canon = etree.tostring(doc, method="c14n2", exclusive=True)
    let lxml_ref = std::fs::read("/tmp/lxml_canonical.xml").unwrap_or_default();
    if lxml_ref.is_empty() {
        println!("SKIP: /tmp/lxml_canonical.xml not found (run Python reference script first)");
        return;
    }

    let compact = std::fs::read_to_string("/tmp/assertion_clean_compact.xml").unwrap();
    let body = seahorse::saml::c14n::remove_signature_element(&compact).unwrap();
    let rust_canon = seahorse::saml::c14n::canonicalize_exclusive(&body, &[]).unwrap();

    let lxml_str = String::from_utf8_lossy(&lxml_ref);
    let rust_str = String::from_utf8_lossy(&rust_canon);

    println!("lxml canonical: {} bytes", lxml_ref.len());
    println!("Rust canonical: {} bytes", rust_canon.len());

    if rust_canon != lxml_ref {
        // Find first difference
        for (i, (a, b)) in rust_canon.iter().zip(lxml_ref.iter()).enumerate() {
            if a != b {
                let start = i.saturating_sub(30);
                let end = (i + 30).min(rust_canon.len()).min(lxml_ref.len());
                println!("First diff at byte {}", i);
                println!("  Rust:  ...{}...", String::from_utf8_lossy(&rust_canon[start..end]));
                println!("  lxml:  ...{}...", String::from_utf8_lossy(&lxml_ref[start..end]));
                break;
            }
        }
        if rust_canon.len() != lxml_ref.len() {
            println!("Length diff: Rust={} vs lxml={}", rust_canon.len(), lxml_ref.len());
            let shorter = rust_canon.len().min(lxml_ref.len());
            let longer_bytes = if rust_canon.len() > lxml_ref.len() { &rust_canon } else { &lxml_ref.to_vec() };
            println!("Extra bytes: {:?}", String::from_utf8_lossy(&longer_bytes[shorter..]));
        }
    }

    assert_eq!(rust_str, lxml_str, "Rust c14n output must match lxml reference");
}

#[test]
fn test_real_assertion_compact_form() {
    // Use the clean compact form (saved by Python script)
    let compact = match std::fs::read_to_string("/tmp/assertion_clean_compact.xml") {
        Ok(c) => c,
        Err(_) => {
            println!("SKIP: /tmp/assertion_clean_compact.xml not found");
            return;
        }
    };

    println!("\n=== Compact form ===");
    println!("Compact length: {} bytes", compact.len());

    // Try validation on compact form
    let report = seahorse::saml::validator::validate_assertion(&compact, None);
    println!("Summary: {:?}", report.summary);
    for check in &report.checks {
        let icon = if check.passed { "PASS" } else { "FAIL" };
        println!("  [{}] {}: {}", icon, check.name, check.detail);
        if let Some(ref diag) = check.diagnostic {
            println!("        Diagnostic: {}", diag);
        }
    }
}
